var question = "DLRURUDLULRDRUDDRLUUUDLDLDLRLRRDRRRLLLLLDDRRRDRRDRRRLRRURLRDUULRLRRDDLULRLLDUDLULURRLRLDUDLURURLDRDDULDRDRDLDLLULULLDDLRRUDULLUULRRLLLURDRLDDLDDLDRLRRLLRURRUURRRRLUDLRDDDDRDULRLLDDUURDUDRLUDULLUDLUDURRDRDUUUUDDUDLLLRLUULRUURDLRLLRRLRLLDLLRLLRRRURLRRLURRLDLLLUUDURUDDLLUURRDRDRRDLLDDLLRDRDRRLURLDLDRDLURLDULDRURRRUDLLULDUDRURULDUDLULULRRRUDLUURRDURRURRLRRLLRDDUUUUUDUULDRLDLLRRUDRRDULLLDUDDUDUURLRDLULUUDLDRDUUUDDDUDLDURRULUULUUULDRUDDLLLDLULLRLRLUDULLDLLRLDLDDDUUDURDDDLURDRRDDLDRLLRLRR\nRLDUDURDRLLLLDDRRRURLLLRUUDDLRDRDDDUDLLUDDLRDURLDRDLLDRULDDRLDDDRLDRDDDRLLULDURRRLULDRLRDRDURURRDUDRURLDRLURDRLUULLULLDLUDUDRDRDDLDDDDRDURDLUDRDRURUDDLLLRLDDRURLLUDULULDDLLLDLUDLDULUUDLRLURLDRLURURRDUUDLRDDDDDRLDULUDLDDURDLURLUURDLURLDRURRLDLLRRUDRUULLRLDUUDURRLDURRLRUULDDLDLDUUDDRLDLLRRRUURLLUURURRURRLLLUDLDRRDLUULULUDDULLUDRLDDRURDRDUDULUDRLRRRUULLDRDRLULLLDURURURLURDLRRLLLDRLDUDLLLLDUUURULDDLDLLRRUDDDURULRLLUDLRDLUUDDRDDLLLRLUURLDLRUURDURDDDLLLLLULRRRURRDLUDLUURRDRLRUDUUUURRURLRDRRLRDRDULLDRDRLDURDDUURLRUDDDDDLRLLRUDDDDDURURRLDRRUUUDLURUUDRRDLLULDRRLRRRLUUUD\nRDRURLLUUDURURDUUULLRDRLRRLRUDDUDRURLLDLUUDLRLLDDURRURLUDUDDURLURLRRURLLURRUDRUDLDRLLURLRUUURRUDDDURRRLULLLLURDLRLLDDRLDRLLRRDLURDLRDLDUDRUULLDUUUDLURRLLRUDDDUUURLURUUDRLRULUURLLRLUDDLLDURULLLDURDLULDLDDUDULUDDULLRDRURDRRLLDLDDDDRUDLDRRLLLRLLLRRULDLRLRLRLLDLRDRDLLUDRDRULDUURRDDDRLLRLDLDRDUDRULUDRDLDLDDLLRULURLLURDLRRDUDLULLDLULLUDRRDDRLRURRLDUDLRRUUDLDRLRLDRLRRDURRDRRDDULURUUDDUUULRLDRLLDURRDLUULLUDRDDDLRUDLRULLDDDLURLURLRDRLLURRRUDLRRLURDUUDRLRUUDUULLRUUUDUUDDUURULDLDLURLRURLRUDLULLULRULDRDRLLLRRDLU\nRRRRDRLUUULLLRLDDLULRUUURRDRDRURRUURUDUULRULULRDRLRRLURDRRRULUUULRRUUULULRDDLLUURRLLDUDRLRRLDDLDLLDURLLUDLDDRRURLDLULRDUULDRLRDLLDLRULLRULLUDUDUDDUULDLUUDDLUDDUULLLLLURRDRULURDUUUDULRUDLLRUUULLUULLLRUUDDRRLRDUDDRULRDLDLLLLRLDDRRRULULLLDLRLURRDULRDRDUDDRLRLDRRDLRRRLLDLLDULLUDDUDDRULLLUDDRLLRRRLDRRURUUURRDLDLURRDLURULULRDUURLLULDULDUDLLULDDUURRRLDURDLUDURLDDRDUDDLLUULDRRLDLLUDRDURLLDRLDDUDURDLUUUUURRUULULLURLDUUULLRURLLLUURDULLUULDRULLUULRDRUULLRUDLDDLRLURRUUDRLRRRULRUUULRULRRLDLUDRRLL\nULRLDLLURDRRUULRDUDDURDDDLRRRURLDRUDDLUDDDLLLRDLRLLRRUUDRRDRUULLLULULUUDRRRDRDRUUUUULRURUULULLULDULURRLURUDRDRUDRURURUDLDURUDUDDDRLRLLLLURULUDLRLDDLRUDDUUDURUULRLLLDDLLLLRRRDDLRLUDDUULRRLLRDUDLLDLRRUUULRLRDLRDUDLLLDLRULDRURDLLULLLRRRURDLLUURUDDURLDUUDLLDDRUUDULDRDRDRDDUDURLRRRRUDURLRRUDUDUURDRDULRLRLLRLUDLURUDRUDLULLULRLLULRUDDURUURDLRUULDURDRRRLLLLLUUUULUULDLDULLRURLUDLDRLRLRLRDLDRUDULDDRRDURDDULRULDRLRULDRLDLLUDLDRLRLRUDRDDR";

function part1(str) {
    const array = str.split('\n');
    let result = "";
    const pos = [1,1];
    // [x, y]
    const map = [[7,4,1],[8,5,2],[9,6,3]];
    // [0,0] => 7; [2,2] => 3;
    array.forEach(line=>{
        const ops = line.split('');
        ops.forEach(op=>{
            switch (op) {
                case 'U':
                    if (pos[1] < 2) pos[1] += 1;
                    break;
                case 'D':
                    if (pos[1] > 0) pos[1] -= 1;
                    break;
                case 'L':
                    if (pos[0] > 0) pos[0] -= 1;
                    break;
                case 'R':
                    if (pos[0] < 2) pos[0] += 1;
                    break;
                default:
                    break;
            }
        });
        const [x, y] = pos;
        result += map[x][y];
    });
    return result;
}

function part2(str) {
    const map = [
        [null, null, '5', null, null],
        [null, 'A', '6', '2', null],
        ['D', 'B', '7', '3', '1'],
        [null, 'C', '8', '4', null],
        [null, null, '9', null, null]
    ];
    let pos = [2, 0]
    // y, x
    const array = str.split('\n');
    let result = '';
    array.forEach(line=>{
        const ops = line.split('');
        ops.forEach(op=>{
            let newPos;
            switch (op) {
                case 'U':
                    newPos = [...pos];
                    newPos[1] += 1;
                    if (inRange(newPos)) pos = newPos;
                    break;
                case 'D':
                    newPos = [...pos];
                    newPos[1] -= 1;
                    if (inRange(newPos)) pos = newPos;
                    break;
                case 'L':
                    newPos = [...pos];
                    newPos[0] -= 1;
                    if (inRange(newPos)) pos = newPos;
                    break;
                case 'R':
                    newPos = [...pos];
                    newPos[0] += 1;
                    if (inRange(newPos)) pos = newPos;
                    break;
                default:
                    break;
            }
        });
        const [x, y] = pos;
        result += map[x][y];
    });
    return result;
}

function inRange(pos) {
    return Math.abs(pos[0] - 2) + Math.abs(pos[1] - 2) <= 2;
}

const assert = require('assert');
describe("part1", ()=>{
    it("should return 1985 when the input is \n'ULL\nRRDDD\nLURDL\nUUUUD'", ()=>{
        assert.equal(part1('ULL\nRRDDD\nLURDL\nUUUUD'), 1985);
    });
})

console.log("The result is: " + part1(question));
console.log("The result is: " + part2(question));
